# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_body.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(997, 843)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.confirm = QtWidgets.QPushButton(self.centralwidget)
        self.confirm.setObjectName("confirm")
        self.gridLayout_2.addWidget(self.confirm, 0, 0, 1, 1)
        self.source = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.source.sizePolicy().hasHeightForWidth())
        self.source.setSizePolicy(sizePolicy)
        self.source.setMaximumSize(QtCore.QSize(2000, 2000))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.source.setFont(font)
        self.source.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.source.setPlainText("")
        self.source.setObjectName("source")
        self.gridLayout_2.addWidget(self.source, 1, 0, 1, 1)
        self.results = QtWidgets.QTabWidget(self.centralwidget)
        self.results.setMaximumSize(QtCore.QSize(2000, 2000))
        self.results.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.results.setFont(font)
        self.results.setObjectName("results")
        self.tab_lexer = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.tab_lexer.sizePolicy().hasHeightForWidth())
        self.tab_lexer.setSizePolicy(sizePolicy)
        self.tab_lexer.setMaximumSize(QtCore.QSize(2000, 2000))
        self.tab_lexer.setObjectName("tab_lexer")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_lexer)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.token_list = QtWidgets.QTableWidget(self.tab_lexer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.token_list.sizePolicy().hasHeightForWidth())
        self.token_list.setSizePolicy(sizePolicy)
        self.token_list.setObjectName("token_list")
        self.token_list.setColumnCount(0)
        self.token_list.setRowCount(0)
        self.horizontalLayout.addWidget(self.token_list)
        self.results.addTab(self.tab_lexer, "")
        self.tab_parser = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.tab_parser.sizePolicy().hasHeightForWidth())
        self.tab_parser.setSizePolicy(sizePolicy)
        self.tab_parser.setMaximumSize(QtCore.QSize(2000, 2000))
        self.tab_parser.setObjectName("tab_parser")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_parser)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stree_widget = QtWidgets.QTreeWidget(self.tab_parser)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.stree_widget.sizePolicy().hasHeightForWidth())
        self.stree_widget.setSizePolicy(sizePolicy)
        self.stree_widget.setMaximumSize(QtCore.QSize(2000, 2000))
        self.stree_widget.setObjectName("stree_widget")
        self.stree_widget.headerItem().setText(0, "1")
        self.verticalLayout_2.addWidget(self.stree_widget)
        self.stree_to_text = QtWidgets.QPushButton(self.tab_parser)
        self.stree_to_text.setObjectName("stree_to_text")
        self.verticalLayout_2.addWidget(self.stree_to_text)
        self.results.addTab(self.tab_parser, "")
        self.tab_code_gen = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.tab_code_gen.sizePolicy().hasHeightForWidth())
        self.tab_code_gen.setSizePolicy(sizePolicy)
        self.tab_code_gen.setMaximumSize(QtCore.QSize(2000, 2000))
        self.tab_code_gen.setObjectName("tab_code_gen")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_code_gen)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.code_gen = QtWidgets.QTextEdit(self.tab_code_gen)
        self.code_gen.setObjectName("code_gen")
        self.horizontalLayout_3.addWidget(self.code_gen)
        self.results.addTab(self.tab_code_gen, "")
        self.gridLayout_2.addWidget(self.results, 1, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 2)
        self.gridLayout_2.setColumnStretch(1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.file = QtWidgets.QMenuBar(MainWindow)
        self.file.setGeometry(QtCore.QRect(0, 0, 997, 26))
        self.file.setObjectName("file")
        self.menuFile = QtWidgets.QMenu(self.file)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.file)
        self.actionOpenFile = QtWidgets.QAction(MainWindow)
        self.actionOpenFile.setObjectName("actionOpenFile")
        self.actionClean_Source = QtWidgets.QAction(MainWindow)
        self.actionClean_Source.setObjectName("actionClean_Source")
        self.menuFile.addAction(self.actionOpenFile)
        self.file.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.results.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MiniC"))
        self.confirm.setText(_translate("MainWindow", "确认"))
        self.results.setTabText(self.results.indexOf(self.tab_lexer), _translate("MainWindow", "词法分析"))
        self.stree_to_text.setText(_translate("MainWindow", "文本形式"))
        self.results.setTabText(self.results.indexOf(self.tab_parser), _translate("MainWindow", "语法分析"))
        self.results.setTabText(self.results.indexOf(self.tab_code_gen), _translate("MainWindow", "代码生成"))
        self.menuFile.setTitle(_translate("MainWindow", "文件"))
        self.actionOpenFile.setText(_translate("MainWindow", "Open Source"))
        self.actionClean_Source.setText(_translate("MainWindow", "Clean Source"))

